---
deployment:
  tasks:
    - export DEPLOYPATH=/home/renewstudy/renew_app
    - /bin/cp -R accounts $DEPLOYPATH/
    - /bin/cp -R templates $DEPLOYPATH/
    - /bin/cp -R study_project $DEPLOYPATH/
    - /bin/cp -R static $DEPLOYPATH/ 2>/dev/null; true
    - /bin/cp manage.py $DEPLOYPATH/
    - /bin/cp passenger_wsgi.py $DEPLOYPATH/
    - /bin/cp requirements.txt $DEPLOYPATH/
