# Generated by Django 3.2.25 on 2026-03-03 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_pmrsurveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionCheckResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('question_id', models.CharField(choices=[('neg_p6_q1', "Why might Mike react more to Coach Ramos's comments?"), ('neg_p7_q1', "How might Mike be feeling after Coach Ramos's comment?"), ('emo_p2_q1', 'Dave is sad because angry thoughts'), ('emo_p2_q2', 'Avoiding friends like Dave'), ('emo_p2_q3', 'Strange Dave fighting mom'), ('emo_p2_q4', 'Dave triggered')], max_length=20)),
                ('incorrect_attempts', models.IntegerField(default=0)),
                ('answered_correctly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attention_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['question_id'],
                'unique_together': {('session_key', 'question_id')},
            },
        ),
    ]
