# Generated by Django 3.2.25 on 2026-03-03 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_attentioncheckresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='IronSpongeResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('school_type', models.CharField(blank=True, max_length=20, null=True)),
                ('school_iron', models.IntegerField(default=0)),
                ('school_sponge', models.IntegerField(default=0)),
                ('school_neither', models.IntegerField(default=0)),
                ('friend_type', models.CharField(blank=True, max_length=20, null=True)),
                ('friend_iron', models.IntegerField(default=0)),
                ('friend_sponge', models.IntegerField(default=0)),
                ('friend_neither', models.IntegerField(default=0)),
                ('family_type', models.CharField(blank=True, max_length=20, null=True)),
                ('family_iron', models.IntegerField(default=0)),
                ('family_sponge', models.IntegerField(default=0)),
                ('family_neither', models.IntegerField(default=0)),
                ('responses_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iron_sponge_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session_key',)},
            },
        ),
    ]
