# Generated by Django 3.2.25 on 2026-03-03 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_ironspongeresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosplanActivityResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('who', models.TextField(blank=True, default='')),
                ('where', models.TextField(blank=True, default='')),
                ('what', models.TextField(blank=True, default='')),
                ('when', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posplan_activity_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session_key',)},
            },
        ),
    ]
