# Generated by Django 3.2.25 on 2026-03-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_posplanactivityresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('statement1_checked', models.BooleanField(default=False)),
                ('statement2_checked', models.BooleanField(default=False)),
                ('statement3_checked', models.BooleanField(default=False)),
                ('statement4_checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
