# Generated by Django 3.2.25 on 2026-03-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_feedbacksurveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksurveyresponse',
            name='responses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
